apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-tmpl-spring-boot-example
  namespace: argo-workflows
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: repo_name
      - name: branch_name
      - name: commit_message
    steps:
      - - name: build
          templateRef:
            name: kaniko-build-image
            template: kaniko-build-loop
          arguments:
            parameters:
              - name: image_name
                value: "ogrizovicm/spring-boot-example"
              - name: image_variant
                value: '{{ printf "{{inputs.parameters.branch_name}}" }}'
              - name: repo
                value: '{{ printf "{{inputs.parameters.repo_name}}" }}'
              - name: commit_message
                value: '{{ printf "{{inputs.parameters.commit_message}}" }}'

